### ISSUE TITLE
handle interfaces in mutations

### ISSUE THREAD

**Issue by keski** [LiUGraphQL/pgschema-to-apischema#16]
The spec is not clear about what to do when generating mutations from types that use interfaces in one or more fields. Since it is not possible to generate an input type based on an interface, this is a special case. The input type used for creating an image in the example below should support any type that implements the `Job` interface (`ThirdPartySearchJob` or `CrawlingJob`):
```
interface Job {
   ...
}

type ThirdPartySearchJob implements Job {
   ...
}

type CrawlingJob implements Job {
   ...
}

type Image implements Content{
    ...
    job: Job!
}

input DataToCreateImage {
   ...
   job: ???
}
```

An option would be to provide separate fields for connecting/creating types implementing the interface. Example:
```
input DataToCreateImage {
   ...
   job: DataToConnectJobOfImage!
}

input DataToConnectJobOfImage {
  id : ID
  dataToCreateThirdPartySearchJob: DataToCreateThirdPartySearchJob
  dataToCreateCrawlingJob: DataToCreateCrawlingJob
}
```
@hartig Do you have any thoughts on this?

**Comment by hartig** [comment]
@keski your idea is exactly what I would have proposed ;-)
However, the naming should be changed: First, we said that these input types should be named `InputToCreate...` and `InputToConnect...`. Next, the pattern for the `InputToConnect...` types is to have a `connect` field and a `create` field (see [https://github.com/LiUGraphQL/pgschema-to-apischema/wiki/Overview-of-the-Approach#51-creating-an-object](https://github.com/LiUGraphQL/pgschema-to-apischema/wiki/Overview-of-the-Approach#51-creating-an-object)). Hence, your example should look as follows.
```
input InputToCreateImage {
   ...
   job: InputToConnectJobOfImage!
}

input InputToConnectJobOfImage {
  connect: ID
  createThirdPartySearchJob: InputToCreateThirdPartySearchJob
  createCrawlingJob: InputToCreateCrawlingJob
}
```

**Comment by keski** [comment]
The generated API schema now uses the correct naming scheme (note that all generated types are now prefixed by a single underscore, e.g., _InputToConnectJobOfImage).
