### ISSUE TITLE
reverse links for traversal

### ISSUE THREAD

**Issue by keski** [LiUGraphQL/pgschema-to-apischema#19]
The spec doesn't specify how reverse links are to be added when a field has an interface as its type. Below is one possible approach, which introduces a new edge for each implementing type. Internally, this means that, in the case of an interface type, ArangoDB requests need to traverse all edge collections generated for the types implementing an interface. 

```graphql
interface Char {
   ...
}

type A {
   value: Char
}

type B implements Char {
   ...
}

type C implements Char {
   ...
}
```
After introduction of inverse links, the extended types would be something like:

```graphql
type B implements Char {
   valueOfA: [A]
   ...
}

type D implements Char {
   valueOfA: [A] # edge name in ArangoDB: EdgeToConnectValueOfAOfD
   ...
}
```
@hartig

**Comment by keski** [comment]
The purpose of the reverse links is primarily to make querying more flexible and expressive. However, do we also want to support data creation via these reverse edges? For example,

```graphql
type A {
   value: B
}

type B {
   name: String!
   _valueOfA: [A] # Reverse link, 1:N
}

input _InputToCreateA {
   value: _InputToConnectB
}

input _InputToConnectA {
   connect: ID!
   create: _InputToCreateA
}

input _InputToCreateB {
    name: String!
    _valueOfA: _InputToConnectA # do we include this field?
}

input _InputToConnectB {
   connect: ID!
   create: _InputToCreateB
}
```
@hartig

**Comment by hartig** [comment]
Since the second question touches a different topic, I have moved it to a separate issue: #20

**Comment by hartig** [comment]
Regarding the original question, I will answer only the part that is related to the generation of the API schema (i.e., ignoring the part about the implementation--that one needs to be discussed in a separate issue in the corresponding gitlab repo).

I am okay with the approach that you are proposing (adding the reverse edge for each implementing type). However, in addition to that, I think that the reverse edge also needs to be added to the interface type itself. Hence, the API schema for your example would become the following:
```graphql
interface Char {
   valueOfA: [A]  # this is added in comparison to your proposal
   ...
}

type B implements Char {
   valueOfA: [A]
   ...
}

type D implements Char {
   valueOfA: [A]
   ...
}
```

**Comment by hartig** [comment]
@keski Can you please open a new issue about the implementation of the approach in the corresponding gitlab project and add me in CC of that issue; I am not sure which project it is.

**Comment by keski** [comment]
The generator now adds the reverse edges to the interface during generation.
