### ISSUE TITLE
filter on returned types

### ISSUE THREAD

**Issue by keski** [LiUGraphQL/pgschema-to-apischema#25]
It should be possible to filter on object types as well as scalars. After discussing this, we've decided on providing a way of filtering on the return types. The pattern supported will be as follows:

```graphql
query {
   listOfPersons(filter: { name: { like: 'John%'} }){
      name
      knows(filter: { name: { like: 'Mary%'} }){
         name
      }
   }
```

This means that all fields referencing an object type need to be extended with a filter argument for that type.
@hartig

**Comment by hartig** [comment]
Robin, just for documentation purposes (and to make sure I understand ;)  ...this issue was about adding the `filter` argument into the `knows` field in your example above, right?
In other words, this issue is about fields definitions that represent outgoing edges. Correct?

In this case, do you add this `filter` to fields whose value type is a **list** of object types (or interfaces or union types)?

Another related question then is: is such a filtering capability also added to the generated fields for reverse traversal of the corresponding edges (e.g., for a field like `_knowsOfPerson` that would be added to the `Person` type)?

**Comment by keski** [comment]
Yes, the filtering capability is also added to the generated fields for reverse traversal with the corresponding filter type.

With regard to filtering over lists, this is supported, but filtering over values that are interfaces is not. The reason for this is related to how how it is implemented. Basically, the current approach adds the argument `filter` to all edge fields. For example,

```graphql
query {
   listOfPersons(filter: { name: { like: 'John%'} }){
      name
      knows(filter: { name: { like: 'Mary%'} }){
         name
      }
   }
}

type Person {
   name: String!
   knows(filter: _FilterForPerson): [Person]
}

input _FilterForPerson {
  _and: [_FilterForPerson]
  _or: [_FilterForPerson]
  _not: _FilterForPerson
  name: _StringFilter
  id: _IDFilter
}
```

Now, let's say `Person` implements an interface `Character`, where characters know other characters but a person knows only persons:

```graphql
type Person implements Character {
   name: String!
   knows(filter: _FilterForPerson): [Person]
}


interface Character {
   name: String!
   knows(filter: _FilterForCharacter): [Character]
}

input _FilterForPerson {
  _and: [_FilterForPerson]
  _or: [_FilterForPerson]
  _not: _FilterForPerson
  name: _StringFilter
  id: _IDFilter
}

input _FilterForCharacter {
  _and: [_FilterForCharacter]
  _or: [_FilterForCharacter]
  _not: _FilterForCharacter
  name: _StringFilter
  id: _IDFilter
}
``` 
In this seconds case there is a conflict, since the implementing type `Person` defines an argument of a type that is not `_FilterForCharacter`. Presently, I'm not sure how we should solve this and I simply leave out the `filters` on fields pointing to interfaces.

**Comment by hartig** [comment]
Thanks for the clarification.

However, your example is actually not only about "fields pointing to interfaces" but it also involves an interface that contains such a field, and that's what is causing the conflict you mention.

Let's ignore such cases and focus only "fields pointing to interfaces" that occur within object types. For instance, assume the following DB schema.
```graphql
interface Character {
   name: String!
}

type Person implements Character {
   name: String!
   knows: [Character]
}
```

Notice that the `Character` interface does not contain the field `knows`. Now, in such cases it should be possible to add the filtering capability to the generated API schema. That is, we may end up with the following API schema.
```graphql
interface Character {
   name: String!
}

type Person implements Character {
   name: String!
   knows(filter: _FilterForCharacter): [Character]
}

input _FilterForCharacter {
  _and: [_FilterForCharacter]
  _or: [_FilterForCharacter]
  _not: _FilterForCharacter
  name: _StringFilter
  id: _IDFilter
}
```
Correct?

**Comment by hartig** [comment]
Another thing about lists: My earlier question was badly phrased. What I actually wanted to know: Do you add the `filter` also to field definitions whose value type is **not** a list. For instance, in case of the following DB schema, will the field `bestFriend` have the `filter` argument in the generated API schema?
```graphql
type Person {
   name: String!
   bestFriend: Person
```

**Comment by keski** [comment]
Yes, currently the `filter` argument is added also for non-lists.
One question regarding this, let's say a user want's to find all `Person` that know someone named "John". The query might look like this:
```graphql
query {
   listOfPersons(limit: 100) {
      content {
         id
         knows(filter: { name: { _eq: "John" } }) {
           id 
         } 
      }
   }
}
```
What is the intended meaning of this query? Do we now return up to 100 persons and then filter on the name (which might return 0 persons), or do we return up to 100 persons for which the filter holds (which would potentially be a very intense query)? 

Similarly, what would be returned in the case below if `Person/123` does not know anyone with the name "John"? Would the entire object returned be null, or only that field?
````graphql
query {
   person(id: "Person/123") {
      id
      knows(filter: { name: { _eq: "John" } }) {
        id
      } 
   }
}

**Comment by hartig** [comment]
> Yes, currently the `filter` argument is added also for non-lists.

It should not.

> One question regarding this, let's say a user want's to find all `Person` that know someone named "John". The query might look like this: [...] What is the intended meaning of this query? Do we now return up to 100 persons and then filter on the name (which might return 0 persons), or do we return up to 100 persons for which the filter holds (which would potentially be a very intense query)?

This query returns a list of up to 100 `Person` objects. Each of these has an `id` field and a `knows` field. The value of the `knows` field is an array that contains as many `Person` objects with the name "John" as the current person knows. For any of the 100 `Person` objects that do not know any person named "John", the value of the `knows` field is the empty array.

> Similarly, what would be returned in the case below if Person/123 does not know anyone with the name "John"? Would the entire object returned be null, or only that field? [...]

Assuming there is a person with this ID, the result is the following:
```graphql
data: {
   id: "Person/123"
   knows: []
}
```
