### ISSUE TITLE
mixing of parts from the DB schema and API schema

### ISSUE THREAD

**Issue by keski** [LiUGraphQL/pgschema-to-apischema#27]
The current generated schema mixes parts from the DB schema and parts from the generated API schema. More precisely, the argument definitions in this field definition may occur only in the DB schema, but they should be removed when generating the API schema. For example, the DB schema:

```graphql
type Person {
    marriedTo(since: Date!): Person
}
```
should in the API schema be rendered as (note that the arguments are accessed via the added fields for edge types):
```graphql
type Person {
    marriedTo: Person
}
```

@hartig

**Comment by hartig** [comment]
Thanks!
